apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: 287489840086.dkr.ecr.ap-southeast-1.amazonaws.com/super30 ecr:7
      imagePullSecrets:
        - name: ecr-registry
